/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Broken Rock Studios",
  "tagline": "Multiplayer and Fun",
  "favicon": "img/favicon.ico",
  "trailingSlash": false,
  "url": "https://brokenrockstudios.com",
  "baseUrl": "/",
  "organizationName": "brokenrockstudios",
  "projectName": "website",
  "deploymentBranch": "gh-pages",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "customFields": {
    "about": {
      "title": "About",
      "description": "About us"
    }
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/home/jimbach/src/website/sidebarsProducts.js",
          "path": "products",
          "routeBasePath": "products",
          "sidebarCollapsible": true
        },
        "blog": {
          "blogTitle": "News",
          "blogDescription": "Discover fun and simple multiplayer games at Broken Rock Studios. Immerse yourself in thoughtful and compelling gameplay developed by gamers. Come play with us!",
          "blogListComponent": "/src/components/BlogListPage",
          "routeBasePath": "/"
        },
        "gtag": {
          "trackingID": "G-595SGCKWD1",
          "anonymizeIP": true
        },
        "theme": {
          "customCss": "/home/jimbach/src/website/src/css/custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "learning",
        "path": "learning",
        "routeBasePath": "learning",
        "sidebarPath": "/home/jimbach/src/website/sidebarsLearning.js"
      }
    ]
  ],
  "themeConfig": {
    "image": "img/logo-500x500.png",
    "metadata": [
      {
        "name": "keywords",
        "content": "broken rock studio, game development, multiplayer"
      }
    ],
    "navbar": {
      "title": "Broken Rock Studios",
      "logo": {
        "alt": "Broken Rock Studios Logo",
        "src": "img/logo.svg",
        "className": "navbar-logo"
      },
      "hideOnScroll": true,
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "productSidebar",
          "position": "left",
          "label": "Products"
        },
        {
          "type": "docSidebar",
          "docsPluginId": "learning",
          "sidebarId": "learningSidebar",
          "position": "left",
          "label": "Learning"
        },
        {
          "to": "https://www.fangamer.com/",
          "label": "Store",
          "position": "left"
        },
        {
          "to": "/about",
          "label": "About",
          "position": "left"
        },
        {
          "href": "https://store.steampowered.com",
          "label": "Buy P1",
          "position": "right",
          "className": "header-p1-link"
        }
      ]
    },
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": true,
      "respectPrefersColorScheme": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Community",
          "items": [
            {
              "label": "Steam",
              "href": "https://store.steampowered.com"
            },
            {
              "label": "Discord",
              "href": "https://discord.gg/sqt6n7Z5xu"
            },
            {
              "label": "Reddit",
              "href": "https://www.reddit.com/r/BrokenRockStudios/"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "News",
              "to": "/"
            }
          ]
        }
      ],
      "copyright": "Copyright © Broken Rock Studios, LLC 2023. All rights reserved."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
